# Generated by Django 5.2.7 on 2025-11-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('Subscription', models.CharField(max_length=255)),
            ],
        ),
    ]
