# Generated by Django 5.2.7 on 2025-11-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uniq',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
